use_frameworks!

target 'RSCustomAlertSheetViewLib_Example' do
  pod 'RSCustomAlertSheetViewLib', :path => '../'

  target 'RSCustomAlertSheetViewLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
